baseurl = "https://lowcostcamp.tk/"
title = "LOW COST CAMP BLOG"
theme = "hugo-creative-portfolio-theme"
languageCode = "ja-jp"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
enableGitInfo = true
publishDir = "docs"
canonifyurls = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "なるべくお金をかけずにキャンプを楽しむためのブログです。"
  copyright = "&copy;2021 hatayan_outdoor"
  sidebarAbout = [
    "なるべくお金をかけずにキャンプを楽しむためのブログです。"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "すべての記事"
  url = "/blog/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  twitter       = "https://twitter.com/hatayan_outdoor"

[taxonomies]
tag = "tags"
category = "categories"

